  sermon_expositivo: {
    label: 'Sermón Expositivo',
    description: 'Formato funcional de guion, pensado para predicar, no para imprimir.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2cm',
      marginBottom: '2cm',
      marginLeft: '2cm',
      marginRight: '2cm',
      bleed: '0cm',
      paperColor: '#ffffff',
    },
    typography: {
      bodyFont: 'Arial',
      bodySize: '13pt',
      lineHeight: 1.8,
      alignment: 'left',
      firstLineIndent: '0cm',
      paragraphSpacing: '8pt',
      hyphenation: false,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Arial', size: '15pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.2em', marginBottom: '0.4em' },
      h2: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.4em' },
      h3: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.3em' },
      h4: { font: 'Arial', size: '13pt', weight: 600, align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'Arial', size: '13pt', weight: 'italic', align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'Arial', size: '13pt', weight: 'normal', align: 'left', lineHeight: 1.3, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: false,
      titlePosition: 'left',
      titleMarginTop: '0cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '',
    },
    headerFooter: {
      header: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      footer: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-center',
      firstPageDifferent: false,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: false, content: '' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'Arial', size: '13pt', lineHeight: 1.8 },
      longQuote: { indentLeft: '1cm', indentRight: '1cm', font: 'Arial', size: '12pt', lineHeight: 1.6, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1cm', bulletChar: '•', subIndent: '1cm', subBulletChar: '◦' },
      numbered: { indent: '1cm', format: '1.', subIndent: '1cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #cccccc',
      headerBg: '#f0f0f0',
      headerFont: 'Arial',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'Arial',
      bodySize: '10pt',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: false,
    },
    notes: {
      footnoteFont: 'Arial',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'Arial',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Contenido',
      tocFont: 'Arial',
      tocSize: '12pt',
      tocLineHeight: 1.5,
      bibleIndex: false,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  video_dinamico: {
    label: 'Video Dinámico',
    description: 'Formato funcional de guion, pensado para grabar, no para imprimir.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2cm',
      marginBottom: '2cm',
      marginLeft: '2cm',
      marginRight: '2cm',
      bleed: '0cm',
      paperColor: '#ffffff',
    },
    typography: {
      bodyFont: 'Arial',
      bodySize: '13pt',
      lineHeight: 1.8,
      alignment: 'left',
      firstLineIndent: '0cm',
      paragraphSpacing: '8pt',
      hyphenation: false,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Arial', size: '15pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.2em', marginBottom: '0.4em' },
      h2: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.4em' },
      h3: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.3em' },
      h4: { font: 'Arial', size: '13pt', weight: 600, align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'Arial', size: '13pt', weight: 'italic', align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'Arial', size: '13pt', weight: 'normal', align: 'left', lineHeight: 1.3, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: false,
      titlePosition: 'left',
      titleMarginTop: '0cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '',
    },
    headerFooter: {
      header: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      footer: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-center',
      firstPageDifferent: false,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: false, content: '' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'Arial', size: '13pt', lineHeight: 1.8 },
      longQuote: { indentLeft: '1cm', indentRight: '1cm', font: 'Arial', size: '12pt', lineHeight: 1.6, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1cm', bulletChar: '•', subIndent: '1cm', subBulletChar: '◦' },
      numbered: { indent: '1cm', format: '1.', subIndent: '1cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #cccccc',
      headerBg: '#f0f0f0',
      headerFont: 'Arial',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'Arial',
      bodySize: '10pt',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: false,
    },
    notes: {
      footnoteFont: 'Arial',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'Arial',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Contenido',
      tocFont: 'Arial',
      tocSize: '12pt',
      tocLineHeight: 1.5,
      bibleIndex: false,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },
