export const BOOK_STYLES = {

  manuscrito_clasico: {
    label: 'Formato Clásico',
    description: 'Estilo editorial estándar para manuscritos listos para revisión.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2.54cm',
      marginBottom: '2.54cm',
      marginLeft: '2.54cm',
      marginRight: '2.54cm',
      bleed: '0cm',
      paperColor: '#ffffff',
    },
    typography: {
      bodyFont: 'Times New Roman',
      bodySize: '12pt',
      lineHeight: 2.0,
      alignment: 'justify',
      firstLineIndent: '1.27cm',
      paragraphSpacing: '0pt',
      hyphenation: false,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Times New Roman', size: '14pt', weight: 'bold', align: 'center', lineHeight: 1.3, marginTop: '1.5em', marginBottom: '0.5em' },
      h2: { font: 'Times New Roman', size: '12pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.25em', marginBottom: '0.5em' },
      h3: { font: 'Times New Roman', size: '12pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '1em', marginBottom: '0.5em' },
      h4: { font: 'Times New Roman', size: '12pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'Times New Roman', size: '12pt', weight: 'italic', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'Times New Roman', size: '12pt', weight: 'normal', align: 'left', lineHeight: 1.4, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: true,
      startNewPage: true,
      titlePosition: 'center',
      titleMarginTop: '6cm',
      numberPrefix: 'Capítulo ',
      numberStyle: 'numeric',
      ornament: '',
    },
    headerFooter: {
      header: { show: true, content: '{author} / {title}', align: 'center', font: 'Times New Roman', fontSize: '10pt', divider: true },
      footer: { show: true, content: '', align: 'center', font: 'Times New Roman', fontSize: '10pt', divider: false },
      pageNumbers: 'top-right',
      firstPageDifferent: true,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: true, content: '', align: 'center' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'Times New Roman', size: '12pt', lineHeight: 2.0 },
      longQuote: { indentLeft: '2.54cm', indentRight: '2.54cm', font: 'Times New Roman', size: '11pt', lineHeight: 1.8, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1.27cm', bulletChar: '•', subIndent: '1.27cm', subBulletChar: '◦' },
      numbered: { indent: '1.27cm', format: '1.', subIndent: '1.27cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #000000',
      headerBg: '#f0f0f0',
      headerFont: 'Times New Roman',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'Times New Roman',
      bodySize: '10pt',
      captionFont: 'Times New Roman',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'Times New Roman',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: true,
    },
    notes: {
      footnoteFont: 'Times New Roman',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'Times New Roman',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Tabla de Contenidos',
      tocFont: 'Times New Roman',
      tocSize: '12pt',
      tocLineHeight: 1.6,
      bibleIndex: false,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  estudio_moderno: {
    label: 'Estudio Moderno',
    description: 'Diseño limpio y contemporáneo para obras académicas o de referencia.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: true,
      marginTop: '2.5cm',
      marginBottom: '2.5cm',
      marginLeft: '3cm',
      marginRight: '2cm',
      bleed: '0.3cm',
      paperColor: '#ffffff',
    },
    typography: {
      bodyFont: 'Georgia',
      bodySize: '11pt',
      lineHeight: 1.6,
      alignment: 'justify',
      firstLineIndent: '0pt',
      paragraphSpacing: '6pt',
      hyphenation: true,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Georgia', size: '18pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.5em', marginBottom: '0.5em' },
      h2: { font: 'Georgia', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.25em', marginBottom: '0.5em' },
      h3: { font: 'Georgia', size: '11pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '1em', marginBottom: '0.5em' },
      h4: { font: 'Georgia', size: '11pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'Georgia', size: '11pt', weight: 'italic', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'Georgia', size: '11pt', weight: 'normal', align: 'left', lineHeight: 1.4, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: true,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: true,
      titlePosition: 'left',
      titleMarginTop: '3cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '',
    },
    headerFooter: {
      header: { show: true, content: '{title}', align: 'center', font: 'Georgia', fontSize: '10pt', divider: true },
      footer: { show: true, content: '', align: 'center', font: 'Georgia', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-center',
      firstPageDifferent: false,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: true, content: '', align: 'center' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'Georgia', size: '11pt', lineHeight: 1.6 },
      longQuote: { indentLeft: '1.5cm', indentRight: '1.5cm', font: 'Georgia', size: '10pt', lineHeight: 1.5, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1.27cm', bulletChar: '–', subIndent: '1.27cm', subBulletChar: '•' },
      numbered: { indent: '1.27cm', format: '1.', subIndent: '1.27cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #cccccc',
      headerBg: '#e8e8e8',
      headerFont: 'Georgia',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'Georgia',
      bodySize: '10pt',
      captionFont: 'Georgia',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'Georgia',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: true,
    },
    notes: {
      footnoteFont: 'Georgia',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'Georgia',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Tabla de Contenidos',
      tocFont: 'Georgia',
      tocSize: '11pt',
      tocLineHeight: 1.5,
      bibleIndex: false,
      subjectIndex: true,
    },
    export: {
      pdfPrint: { cropMarks: true, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  libro_ensenanza: {
    label: 'Libro de Enseñanza',
    description: 'Optimizado para contenido bíblico, didáctico y pastoral.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2cm',
      marginBottom: '2cm',
      marginLeft: '2.2cm',
      marginRight: '2.2cm',
      bleed: '0cm',
      paperColor: '#fefcf5',
    },
    typography: {
      bodyFont: 'EB Garamond',
      bodySize: '11pt',
      lineHeight: 1.5,
      alignment: 'justify',
      firstLineIndent: '0.8cm',
      paragraphSpacing: '4pt',
      hyphenation: true,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Cinzel', size: '16pt', weight: 'bold', align: 'center', lineHeight: 1.3, marginTop: '1.5em', marginBottom: '0.5em' },
      h2: { font: 'Cinzel', size: '12pt', weight: 'normal', align: 'left', lineHeight: 1.3, marginTop: '1.25em', marginBottom: '0.5em' },
      h3: { font: 'Cinzel', size: '11pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '1em', marginBottom: '0.5em' },
      h4: { font: 'EB Garamond', size: '11pt', weight: 'bold', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'EB Garamond', size: '11pt', weight: 'italic', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'EB Garamond', size: '11pt', weight: 'normal', align: 'left', lineHeight: 1.4, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: true,
      titlePosition: 'center',
      titleMarginTop: '4cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '✦',
    },
    headerFooter: {
      header: { show: true, content: '{title}', align: 'center', font: 'EB Garamond', fontSize: '10pt', divider: true },
      footer: { show: true, content: '', align: 'center', font: 'EB Garamond', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-right',
      firstPageDifferent: true,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: true, content: '', align: 'center' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'EB Garamond', size: '11pt', lineHeight: 1.5 },
      longQuote: { indentLeft: '1.5cm', indentRight: '1.5cm', font: 'EB Garamond', size: '10pt', lineHeight: 1.4, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1.27cm', bulletChar: '•', subIndent: '1.27cm', subBulletChar: '◦' },
      numbered: { indent: '1.27cm', format: '1.', subIndent: '1.27cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #d4c5a9',
      headerBg: '#f0ebe0',
      headerFont: 'Cinzel',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'EB Garamond',
      bodySize: '10pt',
      captionFont: 'EB Garamond',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'EB Garamond',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: true,
    },
    notes: {
      footnoteFont: 'EB Garamond',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'EB Garamond',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Tabla de Contenidos',
      tocFont: 'Cinzel',
      tocSize: '11pt',
      tocLineHeight: 1.5,
      bibleIndex: true,
      subjectIndex: true,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  devocional_calido: {
    label: 'Devocional Cálido',
    description: 'Formato íntimo y accesible para lecturas devocionales y reflexiones.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2.2cm',
      marginBottom: '2.2cm',
      marginLeft: '2.5cm',
      marginRight: '2.5cm',
      bleed: '0cm',
      paperColor: '#fefcf5',
    },
    typography: {
      bodyFont: 'EB Garamond',
      bodySize: '12pt',
      lineHeight: 1.7,
      alignment: 'justify',
      firstLineIndent: '0pt',
      paragraphSpacing: '8pt',
      hyphenation: false,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Cinzel', size: '15pt', weight: 'normal', align: 'center', lineHeight: 1.3, marginTop: '1.5em', marginBottom: '0.5em' },
      h2: { font: 'EB Garamond', size: '12pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.25em', marginBottom: '0.5em' },
      h3: { font: 'EB Garamond', size: '11pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '1em', marginBottom: '0.5em' },
      h4: { font: 'EB Garamond', size: '11pt', weight: 'bold', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'EB Garamond', size: '11pt', weight: 'italic', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'EB Garamond', size: '11pt', weight: 'normal', align: 'left', lineHeight: 1.4, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: true,
      titlePosition: 'center',
      titleMarginTop: '3cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '✦',
    },
    headerFooter: {
      header: { show: false, content: '', align: 'center', font: 'EB Garamond', fontSize: '10pt', divider: true },
      footer: { show: false, content: '', align: 'center', font: 'EB Garamond', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-center',
      firstPageDifferent: false,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: true, content: '', align: 'center' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'EB Garamond', size: '12pt', lineHeight: 1.7 },
      longQuote: { indentLeft: '1.5cm', indentRight: '1.5cm', font: 'EB Garamond', size: '11pt', lineHeight: 1.5, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1.27cm', bulletChar: '•', subIndent: '1.27cm', subBulletChar: '◦' },
      numbered: { indent: '1.27cm', format: '1.', subIndent: '1.27cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #d4c5a9',
      headerBg: '#f0ebe0',
      headerFont: 'Cinzel',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'EB Garamond',
      bodySize: '10pt',
      captionFont: 'EB Garamond',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'EB Garamond',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: true,
    },
    notes: {
      footnoteFont: 'EB Garamond',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'EB Garamond',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Contenido',
      tocFont: 'EB Garamond',
      tocSize: '12pt',
      tocLineHeight: 1.6,
      bibleIndex: false,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  sermon_expositivo: {
    label: 'Sermón Expositivo',
    description: 'Formato funcional de guion, pensado para predicar, no para imprimir.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2cm',
      marginBottom: '2cm',
      marginLeft: '2cm',
      marginRight: '2cm',
      bleed: '0cm',
      paperColor: '#ffffff',
    },
    typography: {
      bodyFont: 'Arial',
      bodySize: '13pt',
      lineHeight: 1.8,
      alignment: 'left',
      firstLineIndent: '0cm',
      paragraphSpacing: '8pt',
      hyphenation: false,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Arial', size: '15pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.2em', marginBottom: '0.4em' },
      h2: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.4em' },
      h3: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.3em' },
      h4: { font: 'Arial', size: '13pt', weight: 600, align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'Arial', size: '13pt', weight: 'italic', align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'Arial', size: '13pt', weight: 'normal', align: 'left', lineHeight: 1.3, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: false,
      titlePosition: 'left',
      titleMarginTop: '0cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '',
    },
    headerFooter: {
      header: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      footer: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-center',
      firstPageDifferent: false,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: false, content: '' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'Arial', size: '13pt', lineHeight: 1.8 },
      longQuote: { indentLeft: '1cm', indentRight: '1cm', font: 'Arial', size: '12pt', lineHeight: 1.6, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1cm', bulletChar: '•', subIndent: '1cm', subBulletChar: '◦' },
      numbered: { indent: '1cm', format: '1.', subIndent: '1cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #cccccc',
      headerBg: '#f0f0f0',
      headerFont: 'Arial',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'Arial',
      bodySize: '10pt',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: false,
    },
    notes: {
      footnoteFont: 'Arial',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'Arial',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Contenido',
      tocFont: 'Arial',
      tocSize: '12pt',
      tocLineHeight: 1.5,
      bibleIndex: false,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  video_dinamico: {
    label: 'Video Dinámico',
    description: 'Formato funcional de guion, pensado para grabar, no para imprimir.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2cm',
      marginBottom: '2cm',
      marginLeft: '2cm',
      marginRight: '2cm',
      bleed: '0cm',
      paperColor: '#ffffff',
    },
    typography: {
      bodyFont: 'Arial',
      bodySize: '13pt',
      lineHeight: 1.8,
      alignment: 'left',
      firstLineIndent: '0cm',
      paragraphSpacing: '8pt',
      hyphenation: false,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Arial', size: '15pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.2em', marginBottom: '0.4em' },
      h2: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.4em' },
      h3: { font: 'Arial', size: '13pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1em', marginBottom: '0.3em' },
      h4: { font: 'Arial', size: '13pt', weight: 600, align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'Arial', size: '13pt', weight: 'italic', align: 'left', lineHeight: 1.3, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'Arial', size: '13pt', weight: 'normal', align: 'left', lineHeight: 1.3, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: false,
      titlePosition: 'left',
      titleMarginTop: '0cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '',
    },
    headerFooter: {
      header: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      footer: { show: false, content: '', align: 'center', font: 'Arial', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-center',
      firstPageDifferent: false,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: false, content: '' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'Arial', size: '13pt', lineHeight: 1.8 },
      longQuote: { indentLeft: '1cm', indentRight: '1cm', font: 'Arial', size: '12pt', lineHeight: 1.6, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1cm', bulletChar: '•', subIndent: '1cm', subBulletChar: '◦' },
      numbered: { indent: '1cm', format: '1.', subIndent: '1cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #cccccc',
      headerBg: '#f0f0f0',
      headerFont: 'Arial',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'Arial',
      bodySize: '10pt',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'Arial',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: false,
    },
    notes: {
      footnoteFont: 'Arial',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'Arial',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Contenido',
      tocFont: 'Arial',
      tocSize: '12pt',
      tocLineHeight: 1.5,
      bibleIndex: false,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },

  estudio_predeterminado: {
    label: 'Estudio Bíblico',
    description: 'Formato limpio para estudio bíblico, con énfasis en referencias y aplicación.',
    page: {
      size: 'letter',
      orientation: 'portrait',
      facingPages: false,
      marginTop: '2cm',
      marginBottom: '2cm',
      marginLeft: '2.2cm',
      marginRight: '2.2cm',
      bleed: '0cm',
      paperColor: '#fefcf5',
    },
    typography: {
      bodyFont: 'EB Garamond',
      bodySize: '12pt',
      lineHeight: 1.6,
      alignment: 'justify',
      firstLineIndent: '0pt',
      paragraphSpacing: '6pt',
      hyphenation: true,
      widowOrphanControl: true,
    },
    headings: {
      h1: { font: 'Inter', size: '16pt', weight: 'bold', align: 'left', lineHeight: 1.3, marginTop: '1.5em', marginBottom: '0.5em' },
      h2: { font: 'Inter', size: '13pt', weight: 600, align: 'left', lineHeight: 1.3, marginTop: '1.25em', marginBottom: '0.5em' },
      h3: { font: 'Inter', size: '12pt', weight: 600, align: 'left', lineHeight: 1.4, marginTop: '1em', marginBottom: '0.5em' },
      h4: { font: 'EB Garamond', size: '12pt', weight: 'bold', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h5: { font: 'EB Garamond', size: '12pt', weight: 'italic', align: 'left', lineHeight: 1.4, marginTop: '0.75em', marginBottom: '0.25em' },
      h6: { font: 'EB Garamond', size: '12pt', weight: 'normal', align: 'left', lineHeight: 1.4, marginTop: '0.5em', marginBottom: '0.25em' },
      numbering: false,
      keepWithNext: true,
    },
    chapter: {
      startOnOddPage: false,
      startNewPage: true,
      titlePosition: 'left',
      titleMarginTop: '3cm',
      numberPrefix: '',
      numberStyle: 'numeric',
      ornament: '✦',
    },
    headerFooter: {
      header: { show: true, content: '{title}', align: 'center', font: 'EB Garamond', fontSize: '10pt', divider: true },
      footer: { show: true, content: '', align: 'center', font: 'EB Garamond', fontSize: '10pt', divider: false },
      pageNumbers: 'bottom-right',
      firstPageDifferent: true,
      firstPageHeader: { show: false, content: '' },
      firstPageFooter: { show: true, content: '', align: 'center' },
    },
    blockquotes: {
      shortQuote: { style: 'italic', font: 'EB Garamond', size: '12pt', lineHeight: 1.6 },
      longQuote: { indentLeft: '1.5cm', indentRight: '1.5cm', font: 'EB Garamond', size: '11pt', lineHeight: 1.5, spacingBefore: '6pt', spacingAfter: '6pt' },
    },
    lists: {
      bullet: { indent: '1.27cm', bulletChar: '•', subIndent: '1.27cm', subBulletChar: '◦' },
      numbered: { indent: '1.27cm', format: '1.', subIndent: '1.27cm', subFormat: 'a.' },
    },
    tables: {
      border: '0.5pt solid #d4c5a9',
      headerBg: '#f0ebe0',
      headerFont: 'Inter',
      headerSize: '10pt',
      headerWeight: 'bold',
      cellPadding: '4pt',
      bodyFont: 'EB Garamond',
      bodySize: '10pt',
      captionFont: 'EB Garamond',
      captionSize: '10pt',
      captionStyle: 'italic',
    },
    images: {
      alignment: 'center',
      maxWidth: '100%',
      captionFont: 'EB Garamond',
      captionSize: '10pt',
      captionStyle: 'italic',
      numbering: true,
    },
    notes: {
      footnoteFont: 'EB Garamond',
      footnoteSize: '9pt',
      footnoteLineHeight: 1.2,
      footnoteSeparator: '—',
      endnoteFont: 'EB Garamond',
      endnoteSize: '10pt',
      endnoteLineHeight: 1.4,
    },
    indexes: {
      tocTitle: 'Contenido',
      tocFont: 'Inter',
      tocSize: '12pt',
      tocLineHeight: 1.6,
      bibleIndex: true,
      subjectIndex: false,
    },
    export: {
      pdfPrint: { cropMarks: false, colorProfile: 'CMYK', resolution: '300dpi' },
      pdfDigital: { hyperlinks: true, bookmarks: true, embedFonts: true },
      epub: { css: true, toc: true, cover: true },
      docx: { styles: true, toc: true, trackChanges: false },
    },
  },
};
